name: mini_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Mapbox SDK oficial
  mapbox_maps_flutter: ^2.0.0

  # Localização + geocoding
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # Câmara
  camera: ^0.11.0+2

  # Sensores
  sensors_plus: ^6.0.1

  # Permissões
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
